name: Build Docker Image

on:
  push:
    paths:
      - build-base.sh
      - .github/workflows/build.yml
  schedule:
    - cron: '5 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Login into Github Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login into Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u marcusmu --password-stdin

      - name: Build base and push
        run: ./build-base.sh
  cs-fixer:
    needs: [base]
    runs-on: ubuntu-latest
    steps:
      - name: Get latest PHP-CS-Fixer version
        id: cs_fixer_version
        run: |
          VERSION=$(curl https://api.github.com/repos/PHP-CS-Fixer/PHP-CS-Fixer/releases/latest | jq '.tag_name | ltrimstr("v")' -r)
          echo "CS_FIXER_VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "CS_FIXER_VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Login into Github Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login into Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u marcusmu --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_CS_FIXER_VERSION=${{ steps.cs_fixer_version.outputs.CS_FIXER_VERSION }}
          tags: |
            marcusmu/php-cs-fixer:latest
            marcusmu/php-cs-fixer:${{ steps.cs_fixer_version.outputs.CS_FIXER_VERSION }}
            ghcr.io/m-arcus/php-cs-fixer:latest
            ghcr.io/m-arcus/php-cs-fixer:${{ steps.cs_fixer_version.outputs.CS_FIXER_VERSION }}
